# Generated by Django 4.2.7 on 2023-11-12 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_remove_professor_students_student_my_professor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.TextField(blank=True)),
                ('job_description', models.TextField(blank=True)),
                ('number_of_vaccencies', models.IntegerField(default=1)),
                ('date_posted', models.DateField(auto_now_add=True)),
                ('applied_bys', models.ManyToManyField(blank=True, null=True, to='accounts.student')),
            ],
        ),
    ]
