# Generated by Django 4.2.7 on 2023-11-19 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_rename_professor_notificationp_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='major',
            field=models.TextField(blank=True),
        ),
    ]
