# Generated by Django 4.2.7 on 2023-11-19 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_jobs_major'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='performance_type',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobs',
            name='salary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobs',
            name='working_time',
            field=models.TextField(blank=True),
        ),
    ]
