# Generated by Django 4.2.7 on 2023-11-19 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_student_major'),
        ('mainapp', '0009_jobs_performance_type_jobs_salary_jobs_working_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='salary',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='working_time',
        ),
        migrations.CreateModel(
            name='StudentFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True)),
                ('when', models.DateTimeField(auto_now_add=True)),
                ('selection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.selection')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.student')),
            ],
        ),
    ]
