# Generated by Django 4.2.7 on 2023-11-12 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_company_picture_professor_gender_professor_picture_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='students',
        ),
        migrations.AddField(
            model_name='student',
            name='my_professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.professor'),
        ),
    ]
