# Generated by Django 4.2.7 on 2023-11-12 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_professor_students_student_my_professor'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_resume',
            field=models.FileField(blank=True, null=True, upload_to='student_resumes/'),
        ),
    ]
