# Generated by Django 4.2.7 on 2023-11-19 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_student_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='major',
            field=models.TextField(blank=True),
        ),
    ]
